<?php

class Citrus_Integration_Block_Banner extends Mage_Core_Block_Template
{
    protected function _construct()
    {
        parent::_construct();
        if ($this->hasData('template')) {
            $this->setTemplate($this->getData('template'));
        }
    }

    protected function getBanners($pageType){
        return $this->getCitrusHelper()->getBannerModel()->getBannerByPageType($pageType);
    }
    /**
     * @return false|Citrus_Integration_Helper_Data
     */
    public function getCitrusHelper()
    {
        return Mage::helper('citrusintegration'); // TODO: Change the autogenerated stub
    }
}