<?php
$host = Mage::getStoreConfig('citrus/citrus_group/host', Mage::app()->getStore());
if($host == 1) $hostUrl = trim(Citrus_Integration_Model_Service_Authentication::CITRUS_AU_SERVER, '/');
elseif($host == 2) $hostUrl = trim(Citrus_Integration_Model_Service_Authentication::CITRUS_US_SERVER, '/');
else $hostUrl = trim(Citrus_Integration_Model_Service_Authentication::CITRUS_STAGING_SERVER, '/');
?>
<script type="text/javascript" src="https://assets.citrusad.net/citrusjs/0.1.0/citrus.js"></script>
<script type="text/javascript">
    var citrusAd = CitrusAd.init(
        '<?= $hostUrl ?>',
        {
            disableTracking: false
        }
    );
    var ci = jQuery('.citrus-ads');
    ci.on('click', function () {
        var adId = jQuery(this).attr('data-id');
        citrusAd.reportClick(adId).then(function (result) {
            console.log(result);
        }).catch(function (error) {
            console.log(error);
        });

    });
    ci.each(function () {
        var adId = jQuery(this).attr('data-id');
        citrusAd.reportImpression(adId).then(function (result) {
            console.log(result);
        }).catch(function (error) {
            console.log(error);
        })
    })
</script>
<?php
$op_values = Mage::registry('redirect_op');//->getData('redirect_op');
foreach ($op_values as $op_value):
?>
<script type="text/javascript">
    jQuery('.product-options').ready(function () {
        jQuery(".configurable-swatch-list li#option<?php echo $op_value ?> a span").trigger("click");
    });
</script>
<?php endforeach; ?>