<?php
$bannerEnable = Mage::getStoreConfig('citrus_sync/citrus_banner/enable', Mage::app()->getStore());
if($bannerEnable):
    $categoryAdResponse = Mage::registry('categoryAdResponse');
    $searchAdResponse = Mage::registry('searchAdResponseHeb');
    if($categoryAdResponse)
        $banners = $categoryAdResponse['banners'];
    elseif($searchAdResponse)
        $banners = $searchAdResponse['banners'];
    else $banners = null;
    if($banners): ?>
        <div class="citrus-banner">
            <?php
            foreach ($banners as $banner):
                $banner = $this->getCitrusHelper()->getBannerModel()->load($banner)
                ?>
                <a href="<?= $banner->getData('linkUrl') ?>" data-id="<?= $banner->getCitrusId() ?>" class="citrus-ads"><img src="<?= $banner->getData('imageUrl')?>" alt="<?= $banner->getData('altText')?>"
                    height="<?= $this->getHeight()?>" width="<?= $this->getWidth()?>"></a>
            <?php endforeach;?>
        </div>
<?php
    endif;
endif;
?>