<?php
$bannerEnable = Mage::getStoreConfig('citrus_sync/citrus_banner/enable', Mage::app()->getStore());
if($bannerEnable):
    $categoryAdResponse = Mage::registry('categoryAdResponse');
    $searchAdResponse = Mage::registry('searchAdResponse');
    if($categoryAdResponse)
        $banners = $categoryAdResponse['banners'];
    elseif($searchAdResponse)
        $banners = $searchAdResponse['banners'];
    else $banners = null;

    $uuid = Mage::registry('ad_gen_uuid');
    Mage::helper('citrusintegration')->log('[widget] uuid: ' . $uuid . ', slotId: '. $this->getSlotId()
        .', showing banners (first matching only): ' . json_encode($banners) , __FILE__, __LINE__);

    if($banners): ?>
        <div class="citrus-banner">
            <?php foreach ($banners as $banner):
                if(!$this->getSlotId() || $banner['slotId'] == $this->getSlotId()) {
                ?>
                <a href="<?= $banner['linkUrl'] ?>" data-id="<?= $banner['id'] ?>" class="citrus-ads"><img src="<?= $banner['imageUrl']?>" alt="<?= $banner['altText']?>"
                    height="<?= $this->getHeight()?>" width="<?= $this->getWidth()?>"></a>
                <?php
                  break;
                }
            endforeach;?>
        </div>
<?php
    endif;
endif;
?>