<?php
/** @var $this Citrus_Integration_Block_Adminhtml_System_Config_Form_Button */
?>
<div class="actions button-container">
    <button class="button action-configure"
            type="button"
            data-role="<?php /* @escapeNotVerified */
            echo $this->getId() ?>"
            id="<?php /* @escapeNotVerified */
            echo $this->getId() ?>">
        <span><?php /* @escapeNotVerified */
            echo $this->escapeHtml($this->getLabel()) ?></span>
    </button>
</div>

<div id="message-popup-window-mask" style="display:none;"></div>
<div id="message-popup-window" class="message-popup">
    <div class="message-popup-head">
        <a href="#" onclick="closeMessagePopup(); return false;" title="Close"><span>close</span></a>
        <h2><?php echo $this->getLabel(); ?></h2>
    </div>
    <div class="message-popup-content">
        <div class="message">
            <span class="message-icon message-notice" style="background-image:url(http://widgets.magentocommerce.com/1.9.3.8/SEVERITY_NOTICE.gif);"></span>
            <p class="message-text"></p>
        </div>
        <p><a href="#" onclick="closeMessagePopup()">OK</a></p>
    </div>
</div>

<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.3.2/jquery.min.js"></script>
<script type="text/javascript">// src="http://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js">
    // $j=$(".modal-popup");
    $.noConflict();
    var buttonDataRole = document.getElementById("<?php /* @escapeNotVerified */ echo $this->getId() ?>");
    var queueContinue = document.getElementById("queue_continue");
    if(queueContinue !== 'undefined' && queueContinue !== null ) {
        queueContinue.onclick = function () {
            if (confirm('are you sure you want to add all items?')) {
                var height = $('html-body').getHeight();
                $('message-popup-window-mask').setStyle({'height':height+'px'});
                toggleSelectsUnderBlock($('message-popup-window-mask'), false);
                Element.show('message-popup-window-mask');
                jQuery('#loading-mask').show()
            }
        }
    }
    buttonDataRole.onclick = function () {
        jQuery.ajax({
            type: "GET",
            url: '<?php /* @escapeNotVerified */ echo $this->escapeUrl($this->getButtonUrl()) ?>',
            data: [],
            showLoader: true,
            beforeSend: function(){
                var height = $('html-body').getHeight();
                $('message-popup-window-mask').setStyle({'height':height+'px'});
                toggleSelectsUnderBlock($('message-popup-window-mask'), false);
                Element.show('message-popup-window-mask');
                jQuery('#loading-mask').show()
            },
            success: function (response) {
                console.log(response);
                jQuery('#loading-mask').hide();
                var data = JSON.parse(response);
                console.log(data.message);
                openMessagePopup(
                    data.message
                );
            },
            error: function (response) {
                console.log(response);
                jQuery('#loading-mask').hide();
                openMessagePopup(
                    'Something went wrong with Ajax request, please refresh your browser'
                );
            }
        });
    };

    var messagePopupClosed = false;
    function openMessagePopup(content) {
        var height = $('html-body').getHeight();
        $('message-popup-window-mask').setStyle({'height':height+'px'});
        toggleSelectsUnderBlock($('message-popup-window-mask'), false);
        Element.show('message-popup-window-mask');
        jQuery(document.getElementsByClassName('message-text')).html(content);
        $('message-popup-window').addClassName('show');
    }
    function closeMessagePopup() {
        toggleSelectsUnderBlock($('message-popup-window-mask'), true);
        Element.hide('message-popup-window-mask');
        $('message-popup-window').removeClassName('show');
        messagePopupClosed = true;
    }
    // Event.observe(window, 'load', openMessagePopup);
    Event.observe(window, 'keyup', function(evt) {
        if(messagePopupClosed) return;
        var code;
        if (evt.keyCode) code = evt.keyCode;
        else if (evt.which) code = evt.which;
        if (code == Event.KEY_ESC) {
            closeMessagePopup();
        }
    });

    //]]>
</script>